/* C ++ Programming ANCHOR */
    // Is better than C //
        // 1. Can support data abstracions
        // 2. Supports object oriented programming
        // 3. Supports generic programming

    //Language started in 1979 and was originally known as C with classes, essentially it meant that class files (used in object oriented programming)
        // Were added to the C language, 1983 it was renamed C++ 
            // NOTE C++ is associated with the following
                // 1. classes: A (class) is a user-defined data type that we can use in  our program, and it works as an object constructor
                // 2. objects: An object is created from a class
                // 3. attributes
                // 4. Methods

    